apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Настроить под ваши нужды
  # storageClassName: standard  # Раскомментировать если нужен конкретный storage class
