apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'team-webhook'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
    - name: 'team-webhook'
      webhook_configs:
        - url: 'http://example.org/webhook' # <<< замените на ваш webhook URL

    # Пример Telegram (для справки — НЕ храните токен в ConfigMap в проде):
    # - name: 'telegram'
    #   telegram_configs:
    #     - bot_token: '123456:ABC-DEF'   # замените
    #       chat_id: -111111111111
