apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'team-webhook'
      group_by: ['alertname', 'instance']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: 'team-webhook'
        webhook_configs:
          - url: 'http://team-webhook.monitoring.svc.cluster.local:8080/alert'
            http_config:
              # путь внутри контейнера Alertmanager — соответствует монтированному secret
              bearer_token_file: /etc/alertmanager/secrets/webhook_bearer
            send_resolved: true
