apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: monitoring
spec:
  containers:
  - name: debug
    image: localhost:5000/telegram-webhook:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    env:
    - name: TELEGRAM_BOT_TOKEN
      valueFrom:
        secretKeyRef:
          name: telegram-secret
          key: bot_token
    - name: TELEGRAM_CHAT_ID
      valueFrom:
        secretKeyRef:
          name: telegram-secret
          key: chat_id
    - name: SERVER_PORT
      value: "8080"
