apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      serviceAccountName: alertmanager
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.25.0
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.listen-address=:9093
          ports:
            - name: web
              containerPort: 9093
            - name: cluster
              containerPort: 9094
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
              readOnly: true
            - name: data
              mountPath: /alertmanager
            - name: webhook-secret
              mountPath: /etc/alertmanager/secrets
              readOnly: true
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
        - name: webhook-secret
          secret:
            secretName: alertmanager-webhook-token
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-data
