apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: monitoring # вместо docker сети
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec: 
    # hostNetwork: true # Если нужен доступ к сетевому пространству хоста
      containers: 
      - name: node-exporter
        image: prom/node-exporter:latest
        args: 
          - "--path.procfs=/host/proc"
          - "--path.rootfs=/rootfs"
          - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)"
        ports: 
        - containerPort: 9100
        # hostPort: 9100 # Раскомментируйте для проброса порат на ноду
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        resources: 
          requests: 
            memory: "64Mi"
            cpu: "100m"
          limits: 
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: proc
        hostPath: 
          path: /proc
      - name: sys
        hostPath: 
          path: /sys
      - name: rootfs
        hostPath:
          path: /
