#apiVersion: v1
#kind: Service
#metadata:
#  name: node-exporter-service
#  namespace: monitoring
#spec:
#  type: NodePort
#  externalTrafficPolicy: Cluster
#  selector:
#    app: node-exporter
#  ports:
#    - name: http
#      port: 9100
#      targetPort: 9100
#      nodePort: 30091


apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: ClusterIP
  selector:
    app: node-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9100
      targetPort: 9100

